# Generated by Django 3.0.6 on 2020-05-10 06:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('health_points', models.PositiveIntegerField(default=1)),
                ('max_health', models.PositiveIntegerField(default=1)),
                ('mana_points', models.PositiveIntegerField(default=1)),
                ('max_mana', models.PositiveIntegerField(default=1)),
                ('exp_points', models.PositiveIntegerField(default=1)),
                ('max_exp', models.PositiveIntegerField(default=1)),
                ('level', models.PositiveIntegerField(default=1)),
                ('strength', models.IntegerField(default=0)),
                ('dexterity', models.IntegerField(default=0)),
                ('constitution', models.IntegerField(default=0)),
                ('intelligence', models.IntegerField(default=0)),
                ('wisdom', models.IntegerField(default=0)),
                ('charm', models.IntegerField(default=0)),
                ('sp', models.PositiveIntegerField(default=15)),
                ('character_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cat.Class')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('places', models.PositiveIntegerField(default=1)),
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Character')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('photo', models.FileField(blank=True, null=True, upload_to='profile_images/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Inventory')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cat.Item')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CharacterEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('belt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eqpmt_belt', to='cat.Accessory')),
                ('bottom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eqpmt_bottom', to='cat.Armor')),
                ('brace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eqpmt_brace', to='cat.Accessory')),
                ('chest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eqpmt_chest', to='cat.Armor')),
                ('foot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eqpmt_foot', to='cat.Armor')),
                ('head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eqpmt_head', to='cat.Armor')),
                ('left_hand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eqpmt_left_hand', to='cat.Weapon')),
                ('right_hand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eqpmt_right_hand', to='cat.Weapon')),
                ('ring', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eqpmt_ring', to='cat.Accessory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='character',
            name='equipment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.CharacterEquipment'),
        ),
        migrations.AddField(
            model_name='character',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Profile'),
        ),
        migrations.AddField(
            model_name='character',
            name='race',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cat.Race'),
        ),
    ]
